# Test against this version of NODE.JS
environment:
  matrix:
    - nodejs_version : "6"

# install scripts. runs after repo cloning
install:
  # Get lastest
  -ps: Install-Product node $env:nodejs_version

  # install npm
  -npm install


test_script:
  # Output
  - node --version
  - npm --version
  - npm test_script

build: off
